---
version: '3'
services:
  app:
    build: .
    depends_on:
      - redis
    image: notification-service:latest
    working_dir: /var/app
    user: root
    ports:
      - 3000:3000
    volumes:
      - ./:/var/app
    networks:
      - adorsys
    command: ["npm", "run", "first-start"]
    env_file:
      - .env

  app-testing:
    depends_on:
      - redis
      - app
    image: notification-service:latest
    networks:
      - adorsys
    command: ["npm", "run", "start"]
    env_file:
      - .env

  redis:
    image: redis:5.0.6
    container_name: cache
    command: ["redis-server"]
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - adorsys

networks:
  adorsys:
    driver: bridge
