global:  
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m
rule_files:  
- /etc/prometheus/alert.rules
scrape_configs:  
- job_name: PrometheusApp
  scrape_interval: 5s
  scrape_timeout: 5s
  #metrics_path: /ijdc72jg2ugg2dikkkl236f2rhma6qaz/metrics
  #scheme: https
  static_configs:
  - targets:
    - app1:3000
    - app2:3000
#    labels:
#      app: PrometheusApp
#      sandbox: MyDefaultSandbox
- job_name: 'node'
  static_configs:
  - targets: [ node-exporter:9100 ]

- job_name: 'redis_exporter'
  static_configs:
    - targets:
      - redis_exporter:9121
